[Package]
Name = "Std"
Version = "0.1.4"
Type = "Source"
Description = "Rux standard library"
Authors = ["Rux Contributors <info@rux-lang.dev>"]

[Dependencies]
Windows = "*"
#Windows = { Path = "../Windows" }
