[Package]
Name = "Std"
Version = "0.1.5"
Type = "Source"
Description = "Rux standard library"
Authors = ["Rux Contributors <info@rux-lang.dev>"]

[Dependencies.Target.Linux]
Linux = "*"
#Linux = { Path = "../Linux" }

[Dependencies.Target.MacOS]
MacOS = "*"
#MacOS = { Path = "../MacOS" }

[Dependencies.Target.Windows]
Windows = "*"
#Windows = { Path = "../Windows" }
